import { Bot, Cog } from "lucide-react";
import { Alert, Badge, Card, Stat } from "@/components/ui";
import { fmtMoney, fmtNum, fmtQty } from "@/lib/format";
import type { AnalyzerStrategy, PositionStrategy } from "@/lib/strategy-schema";
import type { StrategyMeta } from "@/lib/types";

const stanceTone: Record<string, "positive" | "negative" | "warning" | "neutral" | "info"> = {
  AVERAGE_DOWN: "info",
  HOLD: "neutral",
  CUT_LOSS: "negative",
  EXIT: "negative",
  TRAIL_STOP: "positive",
  TAKE_PARTIAL_PROFIT: "warning",
  BUY: "positive",
  ACCUMULATE_ON_DIPS: "info",
  WAIT: "neutral",
  AVOID: "negative",
};

const label = (s: string) => s.replace(/_/g, " ").toLowerCase().replace(/^\w/, (c) => c.toUpperCase());

type Props =
  | { kind: "position"; strategy: PositionStrategy; meta: StrategyMeta; currency: string | null }
  | { kind: "analyzer"; strategy: AnalyzerStrategy; meta: StrategyMeta; currency: string | null };

export function StrategyView(props: Props) {
  const { strategy, meta, currency } = props;
  const money = (n: number | null | undefined) => fmtMoney(n, currency);

  return (
    <Card
      title={
        <span className="flex items-center gap-2">
          {props.kind === "position" ? "AI strategy" : "Entry strategy"}
          <Badge tone={stanceTone[strategy.stance] ?? "neutral"}>{label(strategy.stance)}</Badge>
          <Badge>{label(strategy.confidence)} confidence</Badge>
        </span>
      }
    >
      {meta.source === "rule-based" && (
        <div className="mb-4">
          <Alert tone="warning">{meta.fallbackReason ?? "Gemini was unavailable; showing a rule-based strategy."}</Alert>
        </div>
      )}

      <p className="text-sm leading-relaxed text-neutral-800">{strategy.summary}</p>

      <dl className="mt-5 grid grid-cols-2 gap-x-6 gap-y-4 border-t border-neutral-100 pt-4 sm:grid-cols-4">
        {props.kind === "position" ? (
          <>
            <Stat label="Stop-loss" value={money(props.strategy.stopLoss)} />
            <Stat label="Trailing stop" value={props.strategy.trailingStopPct != null ? `${fmtNum(props.strategy.trailingStopPct)}%` : "—"} />
            <Stat
              label="Average-down zone"
              value={props.strategy.averageDownZone ? `${money(props.strategy.averageDownZone.low)} – ${money(props.strategy.averageDownZone.high)}` : "—"}
            />
            <Stat label="Review in" value={`${props.strategy.reviewInDays} days`} />
          </>
        ) : (
          <>
            <Stat label="Buy zone" value={`${money(props.strategy.buyZone.low)} – ${money(props.strategy.buyZone.high)}`} />
            <Stat label="Stop-loss" value={money(props.strategy.stopLoss)} />
            <Stat label="Hold duration" value={props.strategy.holdDuration} />
            <Stat label="Targets" value={props.strategy.targets.length} />
          </>
        )}
      </dl>

      {strategy.targets.length > 0 && (
        <Section title="Exit targets">
          <ul className="space-y-1 text-sm">
            {strategy.targets.map((t, i) => (
              <li key={i} className="flex justify-between gap-4">
                <span className="text-neutral-600">{t.label}</span>
                <span className="num font-medium">{money(t.price)}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}

      {props.kind === "position" ? (
        <Section title="Actions">
          <ol className="space-y-2 text-sm">
            {props.strategy.actions.map((a, i) => (
              <li key={i} className="rounded-md bg-neutral-50 px-3 py-2">
                <div className="flex flex-wrap items-baseline gap-x-3 font-medium text-neutral-900">
                  <span>{a.action}</span>
                  {a.price != null && <span className="num">@ {money(a.price)}</span>}
                  {a.quantity != null && <span className="num text-neutral-600">× {fmtQty(a.quantity)}</span>}
                </div>
                <p className="mt-0.5 text-neutral-600">{a.rationale}</p>
              </li>
            ))}
          </ol>
        </Section>
      ) : (
        props.strategy.rationale.length > 0 && (
          <Section title="Rationale">
            <BulletList items={props.strategy.rationale} />
          </Section>
        )
      )}

      {strategy.risks.length > 0 && (
        <Section title="Risks">
          <BulletList items={strategy.risks} />
        </Section>
      )}

      <footer className="mt-5 border-t border-neutral-100 pt-3 text-xs text-neutral-500">
        <div className="flex items-center gap-1.5">
          {meta.source === "gemini" ? <Bot className="h-3.5 w-3.5" /> : <Cog className="h-3.5 w-3.5" />}
          {meta.source === "gemini" ? `Generated by ${meta.model}` : "Rule-based fallback"}
          {meta.reportId != null && <span>· report #{meta.reportId}</span>}
        </div>
        {meta.attempts.some((a) => !a.ok) && (
          <details className="mt-2">
            <summary className="cursor-pointer hover:text-neutral-800">Model fallback log ({meta.attempts.length} attempts)</summary>
            <ul className="mt-1 space-y-0.5 font-mono text-[11px]">
              {meta.attempts.map((a, i) => (
                <li key={i} className={a.ok ? "text-green-700" : "text-neutral-600"}>
                  {a.ok ? "✓" : "✗"} {a.model}
                  {a.error ? ` — ${a.error}` : ""}
                </li>
              ))}
            </ul>
          </details>
        )}
        <p className="mt-2">Not financial advice. Verify levels against your own analysis before trading.</p>
      </footer>
    </Card>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-5">
      <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-neutral-500">{title}</h3>
      {children}
    </div>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="list-disc space-y-1 pl-5 text-sm text-neutral-700">
      {items.map((r, i) => (
        <li key={i}>{r}</li>
      ))}
    </ul>
  );
}
