"""Generate bundle_imports.py: every module that backend/app imports, written as plain imports.

The application itself ships as a Nuitka-compiled app.pyd, which PyInstaller cannot look inside.
Importing the same modules from a plain-Python file lets PyInstaller see and bundle them.
Run automatically by packaging/build.ps1; safe to run by hand:

    python packaging/backend/gen_bundle_imports.py <backend/app dir> <output file>
"""

import ast
import sys
from pathlib import Path

# Imported lazily / optionally by the app; bundle them when installed, never fail when not.
OPTIONAL = {"torch", "transformers", "chronos", "pandas_ta", "truststore", "huggingface_hub", "winreg"}
EXTRA = [  # loaded dynamically by libraries, invisible to static analysis
    "uvicorn.loops.asyncio",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.lifespan.off",
    "huggingface_hub",
    "truststore",
    "transformers",
    "chronos",
]


def collect(app_dir: Path) -> list[str]:
    mods: set[str] = set()
    for py in app_dir.rglob("*.py"):
        tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                mods.update(a.name for a in node.names)
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                mods.add(node.module)
    mods.update(EXTRA)
    return sorted(m for m in mods if m != "app" and not m.startswith("app."))


def main() -> int:
    app_dir, out = Path(sys.argv[1]), Path(sys.argv[2])
    lines = [
        '"""AUTO-GENERATED by gen_bundle_imports.py - do not edit.',
        "Plain imports of everything app.pyd uses, so PyInstaller bundles them.",
        '"""',
        "# ruff: noqa",
        "",
    ]
    for mod in collect(app_dir):
        if mod.split(".")[0] in OPTIONAL:
            lines += ["try:", f"    import {mod}", "except Exception:", "    pass"]
        else:
            lines.append(f"import {mod}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
